services:
  app:
    build: .
    environment:
      CONFIG_ENV: ${CONFIG_ENV}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}
      PG_WRITE_CONNECTION_STRING: ${PG_WRITE_CONNECTION_STRING}
      PG_READ_CONNECTION_STRING: ${PG_READ_CONNECTION_STRING}
      HTTP_PORT: ${HTTP_PORT}
      HTTP_HOST: ${HTTP_HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      ETHEREUM_CONTRACT_NOSE_WSS_URL: ${ETHEREUM_CONTRACT_NOSE_WSS_URL}
      ETHEREUM_CONTRACT_ADDRESS: ${ETHEREUM_CONTRACT_ADDRESS}
      ETHEREUM_CONTRACT_OWNER_WALLET: ${ETHEREUM_CONTRACT_OWNER_WALLET}
      ETHEREUM_CONTRACT_OWNER_PRIVATE_KEY: ${ETHEREUM_CONTRACT_OWNER_PRIVATE_KEY}
      ETHEREUM_CONTRACT_START_BLOCK_NUMBER: ${ETHEREUM_CONTRACT_START_BLOCK_NUMBER}

    depends_on:
      - db
      - redis
    container_name: app
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
